# Generated by Django 4.0.3 on 2022-03-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_indigameuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='indigameuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
